services:
  - type: web
    name: your-service-name
    env: node
    buildCommand: npm install
    startCommand: node your-script.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
